# Workflow derived from https://github.com/rstudio/shiny-workflows
#
# NOTE: This Shiny team GHA workflow is overkill for most R packages.
# For most R packages it is better to use https://github.com/r-lib/actions
on:
  push:
    branches: [main, rc-**]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1" # every monday

name: Package checks

jobs:
  # website:
  #   uses: rstudio/shiny-workflows/.github/workflows/website.yaml@v1
  # routine:
  #   uses: rstudio/shiny-workflows/.github/workflows/routine.yaml@v1
  # R-CMD-check:
  #   uses: rstudio/shiny-workflows/.github/workflows/R-CMD-check.yaml@v1
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: macOS-latest,   r: 'release'}
          - { os: windows-latest, r: "release" }
          - { os: ubuntu-latest, r: "devel", http-user-agent: "release" }
          - { os: ubuntu-latest, r: "release" }
          - { os: ubuntu-latest, r: "oldrel-1" }

    env:
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # Setup private dependency gridlayout
      - name: Setup SSH key for gridlayout
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent_gridlayout.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GHA_GRIDLAYOUT_DEPLOY_KEY }}"

      - name: Check out gridlayout
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent_gridlayout.sock
        run: |
          git clone git@github.com:rstudio/gridlayout.git

      - name: Install gridlayout
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent_gridlayout.sock
        run: |
          RScript -e "pak::local_install('gridlayout/')"

      # End gridlayout setup
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
